Repository valyala/fasthttp, pull requests merged in 2018-09, with the labels that each got.

#405 Add SOCKS5 dialer
  fasthttpproxy/socks5.go
Labels: pending/investigation

#404 Fix appendQuotedPath to include all allowed characters
  bytesconv.go
  uri_test.go
Labels: pending/investigation

#400 Don't suppresses TLS related errors
  client_test.go
  header.go
  header_test.go
  server_test.go
Labels: pending/investigation

#410 Do case insensitive comparisons for headers and cookies
  client_test.go
  cookie.go
  cookie_test.go
  header.go
Labels: enhancement, pending/investigation

#403 Close the file before trying to rename in SaveMultipartFile
  server.go
  server_test.go
Labels: pending/investigation

#381 Fix Cookie peek
  header.go
  header_test.go
Labels: pending/investigation

#407 Allows for empty content type by default. Fixes #214
  header.go
  header_test.go
  server.go
  server_test.go
Labels: pending/investigation

#373 Fix Request.connectionCloseFast bugs
  header.go
  header_test.go
  server.go
Labels: pending/development, pending/tests
