Repository valyala/fasthttp, pull requests merged in 2019-08, with the labels that each got.

#628 Correctly handle `NoDefaultContentType` without setting an `Content-Type` value
  header.go
  header_test.go
Labels: pending/development, pending/submitter-response

#631 Add ability to set timeout for handshake
  client.go
  client_test.go
Labels: pending/submitter-response

#637 A faster s2b function
  bytesconv.go
Labels: pending/submitter-response

#634 Add fuzzit support
  .travis.yml
  README.md
  fuzzit.sh
  fuzzit/cookie/cookie_fuzz.go
  fuzzit/request/request_fuzz.go
  fuzzit/response/response_fuzz.go
  fuzzit/url/url_fuzz.go
Labels: pending/development

#638 Add stub/wrapper for reuseport.Listen on Windows platforms
  reuseport/reuseport.go
  reuseport/reuseport_error.go
  reuseport/reuseport_test.go
  reuseport/reuseport_windows.go
  reuseport/reuseport_windows_test.go
Labels: pending/submitter-response
